question_data = [
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "In which &quot;Call of Duty&quot; game are the &quot;Apothicons&quot; introduced in the Zombies mode?",
     "correct_answer": "Call Of Duty: Black Ops III",
     "incorrect_answers": ["Call Of Duty: Black Ops", "Call Of Duty: World At War", "Call Of Duty: Black Ops II"]},
    {"type": "multiple", "difficulty": "easy", "category": "Science &amp; Nature",
     "question": "This element, when overcome with extreme heat and pressure, creates diamonds.",
     "correct_answer": "Carbon", "incorrect_answers": ["Nitrogen", "Oxygen", "Hydrogen"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "David Baszucki was a co-founder of ROBLOX Corporation.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "In what year was the first &quot;Mass Effect&quot; game released?", "correct_answer": "2007",
     "incorrect_answers": ["2008", "2009", "2010"]},
    {"type": "multiple", "difficulty": "hard", "category": "Geography",
     "question": "What is the name of rocky region that spans most of eastern Canada?",
     "correct_answer": "Canadian Shield",
     "incorrect_answers": ["Rocky Mountains", "Appalachian Mountains",
                           "Himalayas"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Film",
     "question": "The Queen song `A Kind Of Magic` is featured in which 1986 film?", "correct_answer": "Highlander",
     "incorrect_answers": ["Flash Gordon", "Labyrinth", "Howard the Duck"]},
    {"type": "multiple", "difficulty": "easy", "category": "History",
     "question": "In what year did the Wall Street Crash take place?", "correct_answer": "1929",
     "incorrect_answers": ["1932", "1930", "1925"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "What is the last name of Edward and Alphonse in the Fullmetal Alchemist series.",
     "correct_answer": "Elric", "incorrect_answers": ["Ellis", "Eliek", "Elwood"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Music",
     "question": "&quot;Some people call me the space cowboy&quot; is the first line from what song?",
     "correct_answer": "The Joker",
     "incorrect_answers": ["Fandango", "Take The Money and Run", "Fly Like an Eagle"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Board Games",
     "question": "&quot;PAYDAY: The Heist&quot; is a sequel to the board game &quot;Payday&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Television",
     "question": "Which character was played by Dustin Diamond in the sitcom &#039;Saved by the Bell&#039;?",
     "correct_answer": "Screech", "incorrect_answers": ["Zack", "Mr. Belding", "A.C. Slater"]},
    {"type": "multiple", "difficulty": "hard", "category": "Entertainment: Video Games",
     "question": "In the SHMUP series, &quot;Darius&quot;, what is the name of the antagonist faction you fight against?",
     "correct_answer": "Belsar", "incorrect_answers": ["Bacterion", "Bydo", "Orn Empire"]},
    {"type": "multiple", "difficulty": "medium", "category": "Politics",
     "question": "Which former US president used &quot;Let&#039;s Make America Great Again&quot; as his campaign slogan before Donald Trump&#039;s campaign?",
     "correct_answer": "Ronald Reagan", "incorrect_answers": ["Jimmy Carter", "Gerald Ford", "Richard Nixon"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "What element does the Zinogre use in Monster Hunter?", "correct_answer": "Thunder",
     "incorrect_answers": ["Ice", "Fire", "Water"]},
    {"type": "multiple", "difficulty": "medium", "category": "General Knowledge",
     "question": "What is the defining characteristic of someone who is described as hirsute?",
     "correct_answer": "Hairy", "incorrect_answers": ["Rude", "Funny", "Tall"]}]
